resolver: nightly-2016-09-12
packages:
- '.'
- location:
    git: https://github.com/myfreeweb/msgpack-haskell.git
    commit: 8764b1e2f85076cfc5e402dd178c6972c3228021
  extra-dep: true
  subdirs:
    - msgpack
    - msgpack-rpc
extra-deps: []
flags: {}
extra-package-dbs: []
